# Site settings
title: The Paranoid Tip
email: orbitofdeceit@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Magnet for unwanted social media gurus, tweet bots and online marketing. 
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: orbitofdeceit
github_username:  orbitofdeceit

# Build settings
markdown: kramdown
